name = "JSONLines"
uuid = "24c2b838-1c8b-4567-aca0-d45e60436bb9"
authors = ["Daniel Winkler <danielw2904@disroot.org> and contributors"]
version = "2.0.0"

[deps]
CategoricalArrays = "324d7699-5711-5eae-9e2f-1d82baa6b597"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
Mmap = "a63ad114-7e13-5084-954f-fe012c677804"
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
StructTypes = "856f2bd8-1eba-4b0a-8007-ebc267875bd4"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"

[compat]
OrderedCollections = "1.3"
CategoricalArrays = "0.8"
JSON3 = "1.1"
StructTypes = "1.1"
Tables = "1.0.5"
julia = "^1.4"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
